# Site settings
title: Iliana M. Xygkou
email: ixygkou@gatech.edu
description: Research webpage of Iliana M. Xygkou
domain: ilianaxn.github.io
url: https://ilianaxn.github.io
baseurl: ""

# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Iliana M. Xygkou<br/>
    Ph.D. student<br/>
    <a href="https://scs.gatech.edu/" target="_blank">Computer Science</a><br/>
    <a href="https://www.gatech.edu/" target="_blank">Georgia Institute of Technology</a>

location: >
  <a href="https://inetintel.notion.site/Internet-Intelligence-Research-Lab-d186184563d345bab51901129d812ed6" target="_blank">Internet Intelligence Lab</a><br/>
  Klaus Advanced Computer Building <br/>
  Room 3319 <br/>
  <a href="https://www.gatech.edu/" target="_blank">Georgia Institute of Technology</a>

contact: >
    <a href="mailto:ixygkou@gatech.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact me via email</a> <br/>
    <a href="https://www.linkedin.com/in/iliana-xygkou/" target="_blank"><i class="fa fa-linkedin fa-1x"></i> Message me on LinkedIn</a> <br/>


# Pages shown in navbar
nav_pages:
  - name: about
#  - name: publications
#  - name: talks
  - name: research
  - name: projects
#  - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Xygkou
  first_name: [Iliana M.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
